import turtle
bob = turtle.Turtle()
bob.color("red")
bob.forward(100)
bob.right(90)
bob.color("orange")
bob.forward(100)
bob.right(90)
bob.color("yellow")
bob.forward(100)
bob.right(90)
bob.color("green")
bob.forward(100)